---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present
    - name: Install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: add civo user to docker group
  hosts: all
  become: yes
  tasks:
    - name: add civo user to docker group
      user:
        name: civo
        groups: docker
        append: yes
    - name: reconnect to server session
      meta: reset_connection

- name: Start docker containers
  hosts: all
  vars_files:
    - project-vars
  tasks:
    - name: copy docker compose file to remote server
      copy:
        src: docker-compose.yaml
        dest: /home/civo/docker-compose.yaml
    - name: Docker Login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: akramexp
        password: "{{docker_password}}"
    - name: Start containers from compose
      docker_compose:
        project_src: /home/civo
        state: present